name: 'Generate Auto Changelog'
on:
    push:
        branches:
            - main
jobs:
    main:
        name: 'build'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0
            - name: Generate Auto Changelog
              uses: Evarisk/action-auto-changelog@main
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
